# Generated by Django 5.2 on 2025-04-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_rename_creation_date_auction_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={},
        ),
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auctions",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
