# Generated by Django 5.2 on 2025-04-13 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_auction_options_alter_auction_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ("-price", "-creation_date")},
        ),
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
