# Generated by Django 5.2 on 2025-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_bid_options_auction_auctioneer_alter_bid_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bidder",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
